version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  backend:
    build: ./backend-example-docker
    environment:
      - FRONT_URL=http://localhost:5000
      - DB_HOST=db
      - DB_USERNAME=dbuser
      - DB_PASSWORD=example
      - REDIS=redis
    depends_on:
      - db
    ports:
      - 8000:80
    container_name: backend
    command: npm start
  frontend:
    build: ./frontend-example-docker
    environment:
      - API_URL=api
    ports:
      - 5000:80
    container_name: frontend
    command: npm start