version: '3'

services:
  backend:
    build: ./backend-example-docker
    environment:
      - FRONT_URL=http://localhost:5000
    ports:
      - 8000:8000
    command: npm start
  frontend:
    build: ./frontend-example-docker
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
    command: npm start
