version: '3.5'

services:
  backend:
    build: ./ml-kurkkumopo-backend
    environment:
      - FRONT_URL=http://localhost:3000
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=http://localhost:5000
  training:
    build: ./ml-kurkkumopo-training
    volumes:
      - img:/src/imgs
      - data:/src/data
      - model:/src/model
volumes:
  model:
  img:
  data:
