version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  backend:
    build: ./backend-example-docker
    environment:
      - FRONT_URL=http://localhost:5000
    ports:
      - 8000:80
    container_name: backend
    command: npm start
  frontend:
    build: ./frontend-example-docker
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:80
    container_name: frontend
    command: npm start
